
name: Docker/Flask

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Create .env for docker
      run: echo "DOMAIN=localhost" > .env
    - name: Build the Docker image
      run: COMPOSE_PROFILES=workers docker compose up -d --build --scale more-flask=2
    - name: Wait for app
      run: python ./tests/check_health.py
    - name: Stop Docker
      run: docker compose down
